### ISSUE TITLE
export usePrompt and useConfirm hooks

### ISSUE THREAD

**Issue by Shaddix** [sshyam-gupta/react-router-prompt#101]
Thanks for the lib!

Would you mind exporting the hooks that you have (`usePrompt` and `useConfirm`), so that it'd be possible to use them?

**Comment by sshyam-gupta** [comment]
@Shaddix Open in v0.5.4
You can use it as:

Import 👇🏻
```
import { useConfirm, usePrompt } from "react-router-prompt";
```

`useConfirm` 👇🏻
```
const { isActive, onConfirm, resetConfirmation } = useConfirm(when)
```


`usePrompt` 👇🏻
```
const blocker = usePrompt(when)
```
