### ISSUE TITLE
browser always shows the alert before reload, if 'when' is a function

### ISSUE THREAD

**Issue by komarovalexander** [sshyam-gupta/react-router-prompt#102]
'when' can be the BlockerFunction, in that case condition will be always true regardless the result of 'when'
https://github.com/sshyam-gupta/react-router-prompt/blob/0cfc48045f2d28253cf74336304730429a66cc28/src/hooks/use-prompt.ts#L32

**Comment by sshyam-gupta** [comment]
@komarovalexander Fixed in v0.5.4
