### ISSUE TITLE
Uncaught Error: useBlocker must be used within a data router

### ISSUE THREAD

**Issue by JaLe29** [sshyam-gupta/react-router-prompt#111]
I am getting an error just with your example code

Error
```
Uncaught Error: useBlocker must be used within a data router
```

Code:
```
<ReactRouterPrompt when>
  {({ isActive, onConfirm, onCancel }) => (
    <Modal show={isActive}>
      <div>
        <p>Do you really want to leave?</p>
        <button onClick={onCancel}>Cancel</button>
        <button onClick={onConfirm}>Ok</button>
      </div>
    </Modal>
  )}
</ReactRouterPrompt>
```

Libs:
```
    "react-router-dom": "^6.14.2",
    "react-router-prompt": "^0.5.4",
```

**Comment by JaLe29** [comment]
[react-router-prompt](https://github.com/sshyam-gupta/react-router-prompt#note-%EF%B8%8F)

**Comment by abdulhaseeb13mar** [comment]
hi @JaLe29 i am still getting similar error i am using 
`"react-router-dom": "^6.10.0",
    "react-router-prompt": "^0.5.4",`
    i am configuring routes like this:
![image](https://github.com/sshyam-gupta/react-router-prompt/assets/29409407/b1dcd170-0121-4ac2-bb13-1b4acfe1b7fd)
