### ISSUE TITLE
Types not correctly exported in package.json

### ISSUE THREAD

**Issue by MDransfeld** [sshyam-gupta/react-router-prompt#116]
This error occurs when trying to import in a Typescript project:

![image](https://github.com/sshyam-gupta/react-router-prompt/assets/44373357/0539782c-7271-4c81-8d37-eadb60229e5f)

Seems to be fixed by added "types" to the export in the package.json:

![image](https://github.com/sshyam-gupta/react-router-prompt/assets/44373357/ae40c034-db30-4153-a3f2-9af06e109cdd)

**Comment by nramirez-oa** [comment]
Hi! Any plans to fix this issue? :)

I temporarily fixed this by adding the path to the `tsconfig` file like this:
```json
{
  "compilerOptions": {
    "paths": {
      "react-router-prompt": ["node_modules/react-router-prompt/dist/index.d.ts"]
    }
  },
}
```

**Comment by sshyam-gupta** [comment]
Thanks @sweethuman for the PR. I will take a look at it shortly.
