### ISSUE TITLE
No longer compatible with react-router

### ISSUE THREAD

**Issue by razor-1** [sshyam-gupta/react-router-prompt#123]
react-router v6.19 removed the `unstable_` prefix from useBlocker, which breaks this library.

It should be updated along with the various out of date dependencies if it's still maintained. 

Thank you

**Comment by shakif95** [comment]
Hi, thanks for the nice lib. Is there any update on this?

**Comment by ttmher** [comment]
any news when the fix will be merged?

**Comment by sshyam-gupta** [comment]
Extremely sorry, I didn't get a chance to look at this, will go through the changes. Thanks for the PR

**Comment by sshyam-gupta** [comment]
Release [v0.6.0](https://github.com/sshyam-gupta/react-router-prompt/releases/tag/v0.6.0).
Thank you @andrewbusch7 for your PR here and everyone for keeping patience.
I will be updating the dependencies in the coming days.
