### ISSUE TITLE
Demo Site breaks on refresh 

### ISSUE THREAD

**Issue by imanpalsingh** [sshyam-gupta/react-router-prompt#2]
1. Go to the [demo](https://react-router-prompt.netlify.app/)
2. Visit Prompt
3. Refresh
![Screenshot 2022-05-24 at 3 20 54 PM](https://user-images.githubusercontent.com/49276301/170003788-6ec88542-c136-4f40-a29a-3dc2ffd0995b.png)

**Comment by sshyam-gupta** [comment]
Thanks @imanpalsingh for reporting issue here.
This was because of missing [redirect](https://github.com/sshyam-gupta/react-router-prompt/blob/ab785253550b33d4e0b27a6c0d652ac6fe0bcf6b/example/public/_redirects) file for static page.  This is now fixed.
