### ISSUE TITLE
Go Back and Go Forward browser actions do not work, stuck on Prompt.

### ISSUE THREAD

**Issue by nimajalali** [sshyam-gupta/react-router-prompt#20]
When the ReactRouterPrompt is active and you try to Go Back or Go Forward the prompt will show but onConfirm doesn't continue the browser navigation. The user just stays stuck on the prompt.

Attempted to test commit 7c64c7d79828d2149e021f56b9a25ea1668dc2f5 on https://github.com/sshyam-gupta/react-router-prompt/pull/17 but found the same issue occurs.

**Comment by sshyam-gupta** [comment]
Thanks for creating issue @nimajalali . I will check this today.

**Comment by sshyam-gupta** [comment]
The issue is now resolved with the recent release.
