### ISSUE TITLE
bug:使用浏览器的回退时，会优先执行children而不是when

### ISSUE THREAD

**Issue by Wang-yubo** [sshyam-gupta/react-router-prompt#30]
详细描述一下，当我使用这个工具进行拦截路由跳转时，遇到浏览器回退和路由跳转不一样的效果。使用路由跳转时，先判断了when的条件，然后正常退出；但是用浏览器回退时并没有先判断条件，而是直接打开prompt组件又自己关闭了，但是页面却留在了当前页，再次点击浏览器回退时，才正常退出；
![2081663758054_ pic](https://user-images.githubusercontent.com/59524432/191487806-f18ad391-d058-4b80-b29f-7fd9969cc189.jpg)

**Comment by sshyam-gupta** [comment]
Thanks @Wang-yubo for creating the issue, but sorry I do not understand the language.
Would be great if you can update it in English.

**Comment by Wang-yubo** [comment]
> English

If _when()_ The settlement result of is _flase_， then use _Browser's fallback button_  and use _useNavgite_   The performance of exiting is inconsistent _useNavgite_ Is ok, but use _Browser's fallback button_ Will pop up first _Modal_， And the page remains in the current position, and then click Back for the second time to exit normally. I debugged it and found that it will not be executed first _when_ The default isActive is true
