### ISSUE TITLE
Doesn't work with vite.js

### ISSUE THREAD

**Issue by emi2k01** [sshyam-gupta/react-router-prompt#31]
This is the same problem stated here: https://github.com/vitejs/vite/issues/2139#issuecomment-1024852072

I'm not familiar enough with the build tools to provide a PR and make sure that there's no breaking changes, sorry.

**Comment by sshyam-gupta** [comment]
Thanks @emi2k01 for the issue.
I will check this.

**Comment by SonOfWinter** [comment]
Same problem here.
Have you found a solution to this problem?

**Comment by emi2k01** [comment]
```
import ReactRouterPromptRaw from "react-router-prompt";

const ReactRouterPrompt = (ReactRouterPromptRaw as any).default
  ? (ReactRouterPromptRaw as any).default
  : ReactRouterPromptRaw;
```

then use `<ReactRouterPrompt />`

**Comment by emi2k01** [comment]
@SonOfWinter

**Comment by sshyam-gupta** [comment]
Package now uses vite.js tooling. Should work with new version 0.5.0
Thanks for reporting issue here!
