### ISSUE TITLE
`onCancel`,`onConfirm` requires unnecessary arguments.

### ISSUE THREAD

**Issue by skt-t1-byungi** [sshyam-gupta/react-router-prompt#32]
<img width="840" alt="image" src="https://user-images.githubusercontent.com/16894698/192213240-1e35a961-c2dd-4a9b-99ce-f45893e6a2ae.png">

**Comment by skt-t1-byungi** [comment]
I checked this PR(#17 ).

**Comment by sshyam-gupta** [comment]
Is fixed in latest version 0.5.0 which supports react-router-dom v6.7.0. Let me know if this issue is still present. Thanks!
