### ISSUE TITLE
resetConfirmation is always undefined

### ISSUE THREAD

**Issue by srflp** [sshyam-gupta/react-router-prompt#8]
Hey,
this bit of code seems to do nothing.

https://github.com/sshyam-gupta/react-router-prompt/blob/525a4ed87b435e125bd34b3b24b5547eb5fffef9/src/hooks/use-confirm.ts#L63-L65

Callback passed to useCallback returns nothing, so resetConfirmation is always undefined

**Comment by sshyam-gupta** [comment]
Thanks @srflp for reporting issue here.
That's a good catch! This seems bug with multiple functions and so it is never invoked. We can remove one of the nested function.

Also the API doc is missing for this method.

I am swamped a bit now and so this is open for contribution. I can take up later if no one is available to pick.
