### ISSUE TITLE
"Cannot read properties of null (reading 'useEffect')" when used with React 17

### ISSUE THREAD

**Issue by karol-majewski** [sshyam-gupta/react-router-prompt#88]
Hello and thank you for your work. I gave the latest version a try, and it seems like there's a bug somewhere.

This happens to me when I use the following version of dependencies:

- react 17.0.2
- react-dom 17.0.2
- react-router-dom
- 6.8.1
- react-router-prompt 0.5.1

Reproduction:

https://codesandbox.io/s/react-router-prompt-example-react-router-6-7-forked-p3n31e

I noticed that `react` and `react-dom` are listed both as peer dependencies _and_ regular dependencies — perhaps that could be the cause of a mismatch?

**Comment by sshyam-gupta** [comment]
@karol-majewski you were right, including them in dependencies was the culprit. Fixed it now in latest version v0.5.2.
Please take a look.
Thank you for making this package better.

https://codesandbox.io/s/react-router-prompt-example-react-router-6-7-forked-7eou0z?file=/src/index.js
