### ISSUE TITLE
Breaks when more than one ReactRouterPrompt is used 

### ISSUE THREAD

**Issue by karol-majewski** [sshyam-gupta/react-router-prompt#90]
Reproduction:

https://codesandbox.io/s/react-router-prompt-example-react-router-6-7-forked-ink76d

**Comment by sshyam-gupta** [comment]
@karol-majewski I am trying to reproduce it here https://codesandbox.io/s/react-router-prompt-example-react-router-6-7-forked-j91ukk?file=/src/App.js but it works.
I observed that you have set when to `false`.
Can you please confirm if that was the issue or anything else you are trying to explain?

--
Edit:
Are you trying to use the Component in same page, can you share your use-case?

**Comment by karol-majewski** [comment]
My apologies for being imprecise. I overlooked the fact that dependencies in my CodeSandbox had no fixed versions.

I suspect you have figured it out, but this is the issue I was getting when using react-router-prompt@0.5.0:

<img width="769" alt="CleanShot 2023-04-16 at 22 26 57@2x" src="https://user-images.githubusercontent.com/20233319/232340244-4137fe86-4cef-4e5c-9d3e-c48cd8d1afef.png">

**Comment by sshyam-gupta** [comment]
Yes @karol-majewski you reported it right there and is fixed in v0.5.2
https://github.com/sshyam-gupta/react-router-prompt/issues/88#issuecomment-1435531251
Thank you.

**Comment by karol-majewski** [comment]
Excellent! Thank _you_ 🙇🏻‍♂️
