### ISSUE TITLE
Demo doesn't load

### ISSUE THREAD

**Issue by rollasoc** [sshyam-gupta/react-router-prompt#97]
Not a biggie,

[Demo](https://codesandbox.io/s/react-router-prompt-example-react-router-6-7-y9ug7z?file=/src/App.js)

has error

ModuleNotFoundError
Could not find module in path: 'react-dom/client' relative to '/src/index.js'

**Comment by sshyam-gupta** [comment]
@rollasoc Can you check if any extension is blocking the CDN?
https://github.com/codesandbox/codesandbox-client/issues/2276#issuecomment-546097259
I will plan to move to some hosting provider if we face this often.

**Comment by rollasoc** [comment]
It seems to be working this afternoon.   It wasn't this morning when I tried the link.   (I tried it in Firefox, Chrome and Edge)

There is a couple errors and warnings in the console, but nothing too worrying.

**Comment by sshyam-gupta** [comment]
yes even I saw this error but after trying in incognito it worked fine, seems some issue with Codesandbox.
I will close this issue for now, feel free to re-open if issue persist. Thanks for reporting
